spring:
  datasource:
    url: jdbc:h2:~/fiapdb/cartao-fiap;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  batch:
    jdbc:
      initialize-schema: always
  h2:
    console: 
      enabled: true

file:
  chunk: 10
  resource: lista_alunos.txt