spring:
  datasource:
    url: jdbc:h2:~/fiapdb/cartao-fiap;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
    #driverClassName: org.h2.Driver

  batch:
    jdbc:
      initialize-schema: always
      schema: classpath:schema.sql

  h2:
    console: 
      enabled: true

file:
  chunk: 50
  resource: lista_alunos.txt