create table CLIENTES(
	"ID" BIGINT AUTO_INCREMENT PRIMARY KEY, 
	"NOME" VARCHAR(100) NOT NULL, 
	"MATRICULA" INT NOT NULL,
	"DATA_CADASTRO" TIMESTAMP NOT NULL, 
	"DATA_ATUALIZACAO" TIMESTAMP NOT NULL
);

alter table CLIENTES
add constraint MATRICULA_UNIQUE unique ("MATRICULA");
