create table COMPRAS(
	"ID" BIGINT AUTO_INCREMENT PRIMARY KEY, 
	"CLIENTE_ID" BIGINT NOT NULL,
	"VALOR" DECIMAL(6,2) NOT NULL, 
	"DATA" DATE NOT NULL, 
	"SITUACAO" VARCHAR(30) NOT NULL, 
	"DATA_INCLUSAO" TIMESTAMP NOT NULL, 
	"DATA_ATUALIZACAO" TIMESTAMP NOT NULL
);

alter table COMPRAS
ADD FOREIGN KEY ("CLIENTE_ID") REFERENCES CLIENTES("ID");

